sudo: required
dist: trusty
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
before_script:
  - npm install -g coveralls
script:
  - make test
branches:
  only:
    - master
notifications:
  irc: "irc.freenode.org#hawkular"
after_success:
  - cat ./coverage/lcov.info | coveralls
